info:
  # Blog Information
  title:        "Sven Koschnicke"
  subtitle:     "I create great software and help teams and companies to do the same."
  cover_image:  elevator.jpg
  cover_image_caption: "Image from wallhaven.cc"
  about_image:  moos.jpg
  about_image_caption: "Image from wallhaven.cc"
  logo:         gfxpro-logo-black.png
  author:
    name: Sven Koschnicke
    twitter: svenkoschnicke
    bio: "Software developer."
    image: sven.jpg


  # Social links
  # facebook:     sendtoinc
  twitter:      SvenKoschnicke
  github:       SKoschnicke
  # gplus:        '101183822199340201470'

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname: false

  # Google Analytics tracking ID. Leave blank to disable tracking
  google-analytics-id:

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      false
    hn:         false
    reddit:     true

# Root URL where the site will be published
url:         http://www.gfxpro.com

# host 0.0.0.0 allows us to access site via sapphire.local or localhost or 127.0.0.1
host: 0.0.0.0

paginate:             10
excerpt_separator: "<!-- more -->"

gems: ['jekyll-paginate', jekyll/responsive_image]

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 480
    - width: 800
    - width: 1200
